### ISSUE TITLE
Compile not working on Ubuntu 14.04

### ISSUE THREAD

**Issue by sysads** [sqlitebrowser/sqlitebrowser#68]
I have just tried compiling on ubuntu 14.04 but ran into this error:

sqlitedb.cpp:11:21: fatal error: sqlite3.h: No such file or directory
 #include <sqlite3.h>
                     ^
compilation terminated.
make[2]: **\* [release/sqlitedb.o] Error 1
make[2]: Leaving directory `/home/sysadmin/sqlitebrowser/src'
make[1]: *** [release] Error 2
make[1]: Leaving directory`/home/sysadmin/sqlitebrowser/src'
make: **\* [sub-src-make_default] Error 2

anyone able to assist or successful with ubuntu trusty
