### ISSUE TITLE
New MailWindow.cpp error during compile

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#7]
Just got this when trying to compile:

```
clang++ -c -pipe -O2 -arch x86_64 -fPIC -Wall -W -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang -I. -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/include -I. -Irelease -F/usr/local/Cellar/qt/4.8.6/lib -o release/NoViableAltException.o src/NoViableAltException.cpp
MainWindow.cpp:1565:13: error: unknown type name 'QColorDialog'; did you mean 'QFileDialog'?
            QColorDialog colordialog(this);
            ^~~~~~~~~~~~
            QFileDialog
/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers/qfiledialog.h:66:20: note: 'QFileDialog'
      declared here
class Q_GUI_EXPORT QFileDialog : public QDialog
                   ^
MainWindow.cpp:1568:40: error: no member named 'getColor' in 'QFileDialog'
            QColor color = colordialog.getColor(precolor, this, tr("Choose a axis color"));
                           ~~~~~~~~~~~ ^
2 errors generated.
make[2]: *** [release/MainWindow.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

Seems to have been introduced by https://github.com/sqlitebrowser/sqlitebrowser/commit/da9f24836aa6c31cff129b84a581c923d5fc6b6e.

Maybe it's due to my Qt version?  I have 4.8.6 installed.  Can try 5.x if that would be better.
