### ISSUE TITLE
Errors (and fixes) when building with Qt 4.6

### ISSUE THREAD

**Issue by peteristhegreat** [sqlitebrowser/sqlitebrowser#435]
I just worked through getting it to build on Qt 4.6.2, on a locked down Linux machine.

It struggled with a few errors when building v3.5.1.

Here are the errors:

	main.cpp: In function 'int main(int, char**)':
	main.cpp:115: error: 'QFile' has not been declared
	main.cpp:123: error: 'QFile' has not been declared
	main.cpp:148: error: 'QFile' was not declared in this scope
	main.cpp:148: error: expected ';' before 'file'
	main.cpp:149: error: 'file' was not declared in this scope

	MainWindow.cpp:32:25: error: QElapsedTimer: No such file or directory
	MainWindow.cpp: In member function 'void MainWindow::executeQuery()':
	MainWindow.cpp:749: error: 'QElapsedTimer' was not declared in this scope
	MainWindow.cpp:749: error: expected ';' before 'timer'
	MainWindow.cpp:750: error: 'timer' was not declared in this scope

	EditTableDialog.cpp: In constructor 'EditTableDialog::EditTableDialog(DBBrowserDB*, const QString&, bool, QWidget*)':
	EditTableDialog.cpp:20: error: 'currentMSecsSinceEpoch' is not a member of 'QDateTime'

	ImportCsvDialog.cpp: In member function 'virtual void ImportCsvDialog::accept()':
	ImportCsvDialog.cpp:199: error: 'currentMSecsSinceEpoch' is not a member of 'QDateTime'

	FilterTableHeader.cpp: In constructor 'FilterLineEdit::FilterLineEdit(QWidget*, QList<FilterLineEdit*>*, int)':
	FilterTableHeader.cpp:14: error: 'setPlaceholderText' was not declared in this scope

I'll see about doing a pull request sometime with the fixes.

Fixes basically were:

Add `#include <QFile>` to main.cpp

Wrap includes for `QElaspedTimer` with:

	#if (QT_VERSION < QT_VERSION_CHECK(4, 7, 0))
	# include <QTime>
	typedef QTime QElapsedTimer;
	#else
	# include <QElapsedTimer>
	#endif

Wrap calls to `QDateTime::currentMSecsToEpoch()` with

	#if QT_VERSION < QT_VERSION_CHECK(4, 7, 0)
		QDateTime::currentDateTime().toTime_t() * 1000
	#else
		QDateTime::currentMSecsSinceEpoch()
	#endif

Wrap call to `QLineEdit::setPlaceHolderText()` with

	#if (QT_VERSION < QT_VERSION_CHECK(4, 7, 0))
		// setPlaceHolderText(tr("Filter"));
	#else
		setPlaceHolderText(tr("Filter"));
	#endif

Hope that helps someone.  These fixes should make it backwards compatible with Qt 4.6.

**Comment by justinclift** [comment]
Interesting.  That's good info.  If you submit a PR, I can merge it. :smile:

**Comment by justinclift** [comment]
@peteristhegreat Ping? :smile:

**Comment by justinclift** [comment]
@peteristhegreat Is this issue still of use?

**Comment by peteristhegreat** [comment]
I'll try rebuilding it with 4.6 on a home computer this weekend. I found
those errors on a locked down computer without internet access.  Sorry
about the late response.  Does it still build easily with 4.8 since
supporting qt 5?

-Peter

**Comment by justinclift** [comment]
Yep, it definitely builds with both (at least) Qt4.8 and Qt5.6.

My main dev desktop is OSX, and I'm compiling against Qt4.8 presently.  Was compiling (fine) against Qt 5.6 yesterday. :smile:

**Comment by justinclift** [comment]
@peteristhegreat Any luck? :smile:

**Comment by justinclift** [comment]
@peteristhegreat We're moving to be Qt5-only shortly, so I'm going to close this.  Qt4.6 is kinda not relevant to us any more. :smile:

**Comment by revolter** [comment]
@justinclift, Shouldn't we remove other checks for old Qt versions like [this][1], [this][2] and [this][3]?

  [1]: https://github.com/sqlitebrowser/sqlitebrowser/blob/c5c8106c1caa204f1b897d589b3c9507e8e694bb/src/ColumnDisplayFormatDialog.cpp#L45
  [2]: https://github.com/sqlitebrowser/sqlitebrowser/blob/c5c8106c1caa204f1b897d589b3c9507e8e694bb/src/ColumnDisplayFormatDialog.cpp#L57
  [3]: https://github.com/sqlitebrowser/sqlitebrowser/blob/f33a988530dae9bb6e6faa20b0d47c1c06c609c3/src/FilterLineEdit.cpp#L10

**Comment by innermous** [comment]
I don't think putting #ifdefs everywhere for compatibility with such *outdated* Qt versions is of any good. This slows our dead Qt5 migration even more.

**Comment by justinclift** [comment]
@revolter Sure, when we flip the "Qt5 only" switch for our project, version specific code like that is probably not useful.

As a thought though, if there are version checks around code introducing recent Qt functions (maybe 5.6 onwards?), it's probably best to keep that around for a while.  Not every OS has the latest release of Qt in the 5.x series.

We should probably take a quick look around to see what's available in the major *nix distributions.  RHEL/CentOS and the Ubuntu LTS releases we should probably know about, as least so we can make an informed choice.

**Comment by revolter** [comment]
Sorry, I thought they were checking for Qt 4.5.*

**Comment by justinclift** [comment]
No worries.  It's still a good point. :smile:

**Comment by depontius** [comment]
This is an old thread, but I'll just add that yesterday it saved my hide.  Qt-4.6 may be ancient, but it's what's in use in RedHat 6.8, which is still widely used in industry.  This patch is not irrelevant to me.  Just for jollies, and to be informative, my company-standard installation has qt-1:4.6.2-28 and qt3-3.3.8b-30 installed.  (If you thought Qt-4.6 was old...)  I have qt5-5.6.1-3 available but not installed - apparently nothing "standard" has called for it.  The preparations are beginning to upgrade to RedHat 6.9, but I'm not sure what Qt code levels that will entail or when it will happen.

**Comment by peteristhegreat** [comment]
Awesome!  Glad it was useful.  The biggest thing to watch for with older versions of RedHat is support for OpenGL or the MesaGL libraries and xcb support.  If those are fully installed and supported, then Qt 5 will play nice.  Otherwise some gotchas come up.  Qt 4.8.x doesn't need OpenGL, and Qt Lite (in Qt 5.8+) also doesn't need OpenGL.

**Comment by justinclift** [comment]
@depontius No worries.  When EL 6.9 is released there's roughly a 0% chance it'll come with a largely upgraded version of Qt.  Red Hat is pretty serious about not introducing major binary changes to their major releases, apart from stability and security fixes.  (I worked for Red Hat for a few years, so this isn't an unknown area to me. :wink)

On a side note, we finished migrating our (DB Browser for SQLite) source code to need Qt 5.6 and above, a few months ago.  Technically, it can be made to work with Qt 5.5 (there's a patch we're discussing at the moment), but all things considered... Qt 5.7 is better anyway.  There are bugs in the earlier Qt 5.x releases which turn out to introduce some weirdness.  Not killer weirdness, just some graphical and speed-in-graphical-updates oddities.

**Comment by ZizzyZizzy** [comment]
Thanks for this, that fixed the first couple of issues. on CentOS 6.9.

Now I'm getting more errors:

[ 62%] Building CXX object CMakeFiles/DB Browser for SQLite.dir/src/FilterLineEdit.cpp.o
src/sqlitebrowser-3.9.1/src/FilterLineEdit.cpp: In constructor 'FilterLineEdit::FilterLineEdit(QWidget*, QList<FilterLineEdit*>*, int)':
src/sqlitebrowser-3.9.1/src/FilterLineEdit.cpp:9: error: 'setPlaceholderText' was not declared in this scope

**Comment by tardigradus** [comment]
I had this problem when accessing a database via SSHFS.  The machine with the database was running  SL 6.9, so thanks to @peteristhegreat I was able to build version 3.9.0.
