### PR TITLE
Properly checkout release in windows CI

### PR DESCRIPTION
**Pull request by remysucre**
This should fix the currently broken windows build?

### CODE REVIEW

**Comment by lucydodo** [comment]
Thank you for your interest. First of all, I apologize for the delayed response.

After checking the CI logs, it turns out the issue occurred because the `switch` command did not properly switch the codebase, whereas `checkout` seems to correctly switch the codebase. (Although I’m not sure why it works on the Ubuntu)

That said, I was able to discover this thanks to your PR. I learned something new because of it. Thank you!

**Comment by remysucre** [comment]
The Ubuntu workflow was correctly using `checkout` so the build succeeded. I think the windows build on this PR failed because I did not remove the `SQLITE_EXTRA_*` flags which only work on sqlcipher 4.7?

**Comment by lucydodo** [comment]
Yes, that's correct.  According to the CI logs, the following error can be observed:
```
sqlite3.lo : error LNK2019: unresolved external symbol sqlcipher_extra_init referenced in function sqlite3_initialize
sqlite3.lo : error LNK2019: unresolved external symbol sqlcipher_extra_shutdown referenced in function sqlite3_shutdown
```
